#docker-compose up
version: "3.9"
services:
  postgres:
    container_name: localPostgresSQLDBPortfolio
    image: postgres
    environment:
      POSTGRES_DB: "local_db_portfolio"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5435:5432"
